import { provideIcons } from '@ng-icons/core';
import {
  lucideActivity,
  lucideArchive,
  lucideArchiveRestore,
  lucideArrowDownLeft,
  lucideArrowDownRight,
  lucideArrowRight,
  lucideArrowUpRight,
  lucideBanknote,
  lucideBookOpen,
  lucideBot,
  lucideBriefcase,
  lucideCalendar,
  lucideCalendarClock,
  lucideCalendarDays,
  lucideChartArea,
  lucideChartColumn,
  lucideChartLine,
  lucideChartPie,
  lucideCheck,
  lucideChevronDown,
  lucideChevronLeft,
  lucideChevronRight,
  lucideChevronUp,
  lucideCircleAlert,
  lucideCircleCheck,
  lucideCirclePause,
  lucideCirclePlay,
  lucideCircleX,
  lucideClock,
  lucideCloudDownload,
  lucideCoins,
  lucideCreditCard,
  lucideDownload,
  lucideEye,
  lucideEyeOff,
  lucideFileDown,
  lucideFilePlus,
  lucideFileSpreadsheet,
  lucideFileUp,
  lucideFunnel,
  lucideGauge,
  lucideHandCoins,
  lucideHistory,
  lucideHourglass,
  lucideInbox,
  lucideInfo,
  lucideKeyRound,
  lucideLandmark,
  lucideLanguages,
  lucideLayers,
  lucideLayoutDashboard,
  lucideLink,
  lucideList,
  lucideListChecks,
  lucideLoader2,
  lucideLoaderCircle,
  lucideLock,
  lucideLogOut,
  lucideMail,
  lucideMenu,
  lucideMonitor,
  lucideMoon,
  lucideOctagonX,
  lucidePalette,
  lucidePause,
  lucidePencil,
  lucidePercent,
  lucidePiggyBank,
  lucidePlay,
  lucidePlug,
  lucidePlus,
  lucidePower,
  lucideReceipt,
  lucideRefreshCw,
  lucideRepeat,
  lucideRotateCcw,
  lucideSave,
  lucideScale,
  lucideSearch,
  lucideSend,
  lucideSettings,
  lucideShieldCheck,
  lucideShoppingCart,
  lucideSkipForward,
  lucideSparkles,
  lucideSquarePen,
  lucideSun,
  lucideSunMoon,
  lucideTags,
  lucideTarget,
  lucideTrash2,
  lucideTrendingDown,
  lucideTrendingUp,
  lucideTriangleAlert,
  lucideTrophy,
  lucideUndo2,
  lucideUnplug,
  lucideUpload,
  lucideUserRound,
  lucideWallet,
  lucideX,
} from '@ng-icons/lucide';

/**
 * The app's single icon set (Lucide, the shadcn/spartan standard). Each icon is imported by name, so
 * only these end up in the bundle. Components add \`providers: [APP_ICONS]\` and use any name below.
 */
export const APP_ICONS = provideIcons({
  lucideActivity,
  lucideArchive,
  lucideArchiveRestore,
  lucideArrowDownLeft,
  lucideArrowDownRight,
  lucideArrowRight,
  lucideArrowUpRight,
  lucideBanknote,
  lucideBookOpen,
  lucideBot,
  lucideBriefcase,
  lucideCalendar,
  lucideCalendarClock,
  lucideCalendarDays,
  lucideChartArea,
  lucideChartColumn,
  lucideChartLine,
  lucideChartPie,
  lucideCheck,
  lucideChevronDown,
  lucideChevronLeft,
  lucideChevronRight,
  lucideChevronUp,
  lucideCircleAlert,
  lucideCircleCheck,
  lucideCirclePause,
  lucideCirclePlay,
  lucideCircleX,
  lucideClock,
  lucideCloudDownload,
  lucideCoins,
  lucideCreditCard,
  lucideDownload,
  lucideEye,
  lucideEyeOff,
  lucideFileDown,
  lucideFilePlus,
  lucideFileSpreadsheet,
  lucideFileUp,
  lucideFunnel,
  lucideGauge,
  lucideHandCoins,
  lucideHistory,
  lucideHourglass,
  lucideInbox,
  lucideInfo,
  lucideKeyRound,
  lucideLandmark,
  lucideLanguages,
  lucideLayers,
  lucideLayoutDashboard,
  lucideLink,
  lucideList,
  lucideListChecks,
  lucideLoader2,
  lucideLoaderCircle,
  lucideLock,
  lucideLogOut,
  lucideMail,
  lucideMenu,
  lucideMonitor,
  lucideMoon,
  lucideOctagonX,
  lucidePalette,
  lucidePause,
  lucidePencil,
  lucidePercent,
  lucidePiggyBank,
  lucidePlay,
  lucidePlug,
  lucidePlus,
  lucidePower,
  lucideReceipt,
  lucideRefreshCw,
  lucideRepeat,
  lucideRotateCcw,
  lucideSave,
  lucideScale,
  lucideSearch,
  lucideSend,
  lucideSettings,
  lucideShieldCheck,
  lucideShoppingCart,
  lucideSkipForward,
  lucideSparkles,
  lucideSquarePen,
  lucideSun,
  lucideSunMoon,
  lucideTags,
  lucideTarget,
  lucideTrash2,
  lucideTrendingDown,
  lucideTrendingUp,
  lucideTriangleAlert,
  lucideTrophy,
  lucideUndo2,
  lucideUnplug,
  lucideUpload,
  lucideUserRound,
  lucideWallet,
  lucideX,
});

/** Sidebar icon per route; page headers reuse it so a page and its nav entry always match. */
export const PAGE_ICONS = {
  dashboard: 'lucideLayoutDashboard',
  monthly: 'lucideCalendarDays',
  annual: 'lucideChartColumn',
  transactions: 'lucideList',
  recurring: 'lucideRepeat',
  budgets: 'lucideChartPie',
  goals: 'lucideTarget',
  portfolio: 'lucideBriefcase',
  netWorth: 'lucideTrendingUp',
  assistant: 'lucideSparkles',
  connections: 'lucideLink',
  accounts: 'lucideWallet',
  categories: 'lucideTags',
  import: 'lucideUpload',
  export: 'lucideDownload',
  ai: 'lucideKeyRound',
  settings: 'lucideSettings',
} as const;
