// <auto-generated />
using System;
using System.Collections.Generic;
using Ai.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ai.Infrastructure.Migrations
{
    [DbContext(typeof(AiDbContext))]
    [Migration("20261005103639_AiWriteAccess")]
    partial class AiWriteAccess
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ai")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ai.Application.Domain.AiAuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Arguments")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("jsonb")
                        .HasColumnName("arguments");

                    b.Property<DateTimeOffset>("AtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at_utc");

                    b.Property<string>("Changes")
                        .HasMaxLength(200)
                        .HasColumnType("jsonb")
                        .HasColumnName("changes");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientName")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("client_name");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("decision");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("Reason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("reason");

                    b.Property<int>("RecordCount")
                        .HasColumnType("integer")
                        .HasColumnName("record_count");

                    b.Property<Guid?>("RecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("record_id");

                    b.Property<int>("ResponseBytes")
                        .HasColumnType("integer")
                        .HasColumnName("response_bytes");

                    b.Property<string>("Scope")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("scope");

                    b.Property<string>("Tool")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tool");

                    b.Property<bool>("Write")
                        .HasColumnType("boolean")
                        .HasColumnName("write");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("AtUtc")
                        .HasDatabaseName("ix_audit_events_at_utc");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_audit_events_client_id");

                    b.ToTable("audit_events", "ai");
                });

            modelBuilder.Entity("Ai.Application.Domain.AiClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<bool>("Internal")
                        .HasColumnType("boolean")
                        .HasColumnName("internal");

                    b.Property<DateTimeOffset?>("LastUsedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.Property<int>("RateLimitPerMinute")
                        .HasColumnType("integer")
                        .HasColumnName("rate_limit_per_minute");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.PrimitiveCollection<List<string>>("Scopes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("scopes");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<string>("TokenPrefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("token_prefix");

                    b.Property<int>("WritesPerHour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(20)
                        .HasColumnName("writes_per_hour");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.HasIndex("TokenPrefix")
                        .IsUnique()
                        .HasDatabaseName("ix_clients_token_prefix");

                    b.ToTable("clients", "ai");
                });

            modelBuilder.Entity("Ai.Application.Domain.AiRecycledItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("client_name");

                    b.Property<DateTimeOffset>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("PurgeAfterUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purge_after_utc");

                    b.Property<DateTimeOffset?>("PurgedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purged_at_utc");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("record_id");

                    b.Property<DateTimeOffset?>("RestoredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("restored_at_utc");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("summary");

                    b.HasKey("Id")
                        .HasName("pk_recycle_bin");

                    b.HasIndex("PurgeAfterUtc")
                        .HasDatabaseName("ix_recycle_bin_purge_after_utc");

                    b.HasIndex("RecordId")
                        .HasDatabaseName("ix_recycle_bin_record_id");

                    b.ToTable("recycle_bin", "ai");
                });

            modelBuilder.Entity("Ai.Application.Domain.AiWriteReceipt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ArgumentsHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("arguments_hash");

                    b.Property<DateTimeOffset>("AtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at_utc");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("jsonb")
                        .HasColumnName("result");

                    b.Property<string>("Tool")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tool");

                    b.HasKey("Id")
                        .HasName("pk_write_receipts");

                    b.HasIndex("AtUtc")
                        .HasDatabaseName("ix_write_receipts_at_utc");

                    b.HasIndex("ClientId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_write_receipts_client_id_key");

                    b.ToTable("write_receipts", "ai");
                });
#pragma warning restore 612, 618
        }
    }
}
