<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="EFCore.NamingConventions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ai.Application\Ai.Application.csproj" />
  </ItemGroup>
</Project>
