// <auto-generated />
using System;
using Investments.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Investments.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InvestmentsDbContext))]
    [Migration("20261001175417_PriceHistory")]
    partial class PriceHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("investments")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Investments.Domain.AssetValuation", b =>
                {
                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<decimal>("Value")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("value");

                    b.HasKey("AssetId", "Date")
                        .HasName("pk_asset_valuation");

                    b.ToTable("asset_valuation", "investments");
                });

            modelBuilder.Entity("Investments.Domain.BrokerSymbol", b =>
                {
                    b.Property<string>("Source")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<string>("Symbol")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("symbol");

                    b.Property<Guid>("SecurityId")
                        .HasColumnType("uuid")
                        .HasColumnName("security_id");

                    b.HasKey("Source", "Symbol")
                        .HasName("pk_broker_symbols");

                    b.HasIndex("SecurityId")
                        .HasDatabaseName("ix_broker_symbols_security_id");

                    b.ToTable("broker_symbols", "investments");
                });

            modelBuilder.Entity("Investments.Domain.CashBalance", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("SyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at_utc");

                    b.HasKey("AccountId", "Currency")
                        .HasName("pk_cash_balances");

                    b.ToTable("cash_balances", "investments");
                });

            modelBuilder.Entity("Investments.Domain.CashMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<decimal>("BaseAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("base_amount");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_cash_movements");

                    b.HasIndex("AccountId", "OccurredAtUtc")
                        .HasDatabaseName("ix_cash_movements_account_id_occurred_at_utc");

                    b.HasIndex("Source", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_cash_movements_source_external_id");

                    b.ToTable("cash_movements", "investments");
                });

            modelBuilder.Entity("Investments.Domain.Dividend", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_id");

                    b.Property<decimal>("GrossAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("gross_amount");

                    b.Property<decimal>("NetAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("net_amount");

                    b.Property<decimal>("NetBaseAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("net_base_amount");

                    b.Property<DateOnly>("PaidOn")
                        .HasColumnType("date")
                        .HasColumnName("paid_on");

                    b.Property<Guid>("SecurityId")
                        .HasColumnType("uuid")
                        .HasColumnName("security_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<bool>("WithholdingDerived")
                        .HasColumnType("boolean")
                        .HasColumnName("withholding_derived");

                    b.Property<decimal>("WithholdingTax")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("withholding_tax");

                    b.HasKey("Id")
                        .HasName("pk_dividends");

                    b.HasIndex("PaidOn")
                        .HasDatabaseName("ix_dividends_paid_on");

                    b.HasIndex("SecurityId")
                        .HasDatabaseName("ix_dividends_security_id");

                    b.HasIndex("Source", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_dividends_source_external_id");

                    b.ToTable("dividends", "investments");
                });

            modelBuilder.Entity("Investments.Domain.FxRate", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Quote")
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("quote")
                        .IsFixedLength();

                    b.Property<decimal>("Rate")
                        .HasPrecision(19, 10)
                        .HasColumnType("numeric(19,10)")
                        .HasColumnName("rate");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("source");

                    b.HasKey("Date", "Quote")
                        .HasName("pk_fx_rates");

                    b.ToTable("fx_rates", "investments");
                });

            modelBuilder.Entity("Investments.Domain.ManualAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_manual_assets");

                    b.ToTable("manual_assets", "investments");
                });

            modelBuilder.Entity("Investments.Domain.MarketPrice", b =>
                {
                    b.Property<Guid>("SecurityId")
                        .HasColumnType("uuid")
                        .HasColumnName("security_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<decimal>("Close")
                        .HasPrecision(19, 8)
                        .HasColumnType("numeric(19,8)")
                        .HasColumnName("close");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.HasKey("SecurityId", "Date")
                        .HasName("pk_market_prices");

                    b.ToTable("market_prices", "investments");
                });

            modelBuilder.Entity("Investments.Domain.NetWorthSnapshot", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<decimal>("AssetsBase")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("assets_base");

                    b.Property<string>("Breakdown")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("jsonb")
                        .HasColumnName("breakdown");

                    b.Property<decimal>("LiabilitiesBase")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("liabilities_base");

                    b.HasKey("Date")
                        .HasName("pk_net_worth_snapshots");

                    b.ToTable("net_worth_snapshots", "investments");
                });

            modelBuilder.Entity("Investments.Domain.PortfolioSnapshot", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<decimal>("CashBase")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("cash_base");

                    b.Property<int>("EstimatedHoldings")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_holdings");

                    b.Property<decimal>("MarketValueBase")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("market_value_base");

                    b.Property<decimal>("NetFlowBase")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("net_flow_base");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("origin");

                    b.HasKey("AccountId", "Date")
                        .HasName("pk_portfolio_snapshots");

                    b.ToTable("portfolio_snapshots", "investments");
                });

            modelBuilder.Entity("Investments.Domain.Position", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Guid>("SecurityId")
                        .HasColumnType("uuid")
                        .HasColumnName("security_id");

                    b.Property<decimal>("AveragePrice")
                        .HasPrecision(19, 8)
                        .HasColumnType("numeric(19,8)")
                        .HasColumnName("average_price");

                    b.Property<decimal>("LastPrice")
                        .HasPrecision(19, 8)
                        .HasColumnType("numeric(19,8)")
                        .HasColumnName("last_price");

                    b.Property<DateTimeOffset>("PriceAsOfUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("price_as_of_utc");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("quantity");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("SyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at_utc");

                    b.HasKey("AccountId", "SecurityId")
                        .HasName("pk_positions");

                    b.HasIndex("SecurityId")
                        .HasDatabaseName("ix_positions_security_id");

                    b.ToTable("positions", "investments");
                });

            modelBuilder.Entity("Investments.Domain.PriceListing", b =>
                {
                    b.Property<Guid>("SecurityId")
                        .HasColumnType("uuid")
                        .HasColumnName("security_id");

                    b.Property<DateOnly?>("CoveredFrom")
                        .HasColumnType("date")
                        .HasColumnName("covered_from");

                    b.Property<DateOnly?>("CoveredTo")
                        .HasColumnType("date")
                        .HasColumnName("covered_to");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at_utc");

                    b.Property<string>("Symbol")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("symbol");

                    b.HasKey("SecurityId")
                        .HasName("pk_price_listings");

                    b.ToTable("price_listings", "investments");
                });

            modelBuilder.Entity("Investments.Domain.Security", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetClass")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("asset_class");

                    b.Property<string>("AssetClassOverride")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("asset_class_override");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<string>("Exchange")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("exchange");

                    b.Property<string>("Isin")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("isin");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("symbol");

                    b.HasKey("Id")
                        .HasName("pk_securities");

                    b.HasIndex("Isin")
                        .IsUnique()
                        .HasDatabaseName("ix_securities_isin")
                        .HasFilter("isin IS NOT NULL");

                    b.ToTable("securities", "investments");
                });

            modelBuilder.Entity("Investments.Domain.TargetAllocation", b =>
                {
                    b.Property<string>("AssetClass")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("asset_class");

                    b.Property<decimal>("Percent")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("percent");

                    b.HasKey("AssetClass")
                        .HasName("pk_target_allocations");

                    b.ToTable("target_allocations", "investments");
                });

            modelBuilder.Entity("Investments.Domain.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<decimal>("BaseAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("base_amount");

                    b.Property<decimal>("CostsBase")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("costs_base");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("ExecutedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at_utc");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_id");

                    b.Property<decimal>("Fees")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("fees");

                    b.Property<decimal>("Price")
                        .HasPrecision(19, 8)
                        .HasColumnType("numeric(19,8)")
                        .HasColumnName("price");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("quantity");

                    b.Property<decimal?>("RealizedPnlBase")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("realized_pnl_base");

                    b.Property<Guid>("SecurityId")
                        .HasColumnType("uuid")
                        .HasColumnName("security_id");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("side");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<decimal>("Taxes")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("taxes");

                    b.HasKey("Id")
                        .HasName("pk_trades");

                    b.HasIndex("SecurityId")
                        .HasDatabaseName("ix_trades_security_id");

                    b.HasIndex("AccountId", "ExecutedAtUtc")
                        .HasDatabaseName("ix_trades_account_id_executed_at_utc");

                    b.HasIndex("Source", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_trades_source_external_id");

                    b.ToTable("trades", "investments");
                });

            modelBuilder.Entity("Investments.Domain.AssetValuation", b =>
                {
                    b.HasOne("Investments.Domain.ManualAsset", null)
                        .WithMany("Valuations")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asset_valuation_manual_assets_asset_id");
                });

            modelBuilder.Entity("Investments.Domain.BrokerSymbol", b =>
                {
                    b.HasOne("Investments.Domain.Security", null)
                        .WithMany()
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_broker_symbols_securities_security_id");
                });

            modelBuilder.Entity("Investments.Domain.Dividend", b =>
                {
                    b.HasOne("Investments.Domain.Security", null)
                        .WithMany()
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dividends_securities_security_id");
                });

            modelBuilder.Entity("Investments.Domain.Position", b =>
                {
                    b.HasOne("Investments.Domain.Security", null)
                        .WithMany()
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_positions_securities_security_id");
                });

            modelBuilder.Entity("Investments.Domain.PriceListing", b =>
                {
                    b.HasOne("Investments.Domain.Security", null)
                        .WithMany()
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_price_listings_securities_security_id");
                });

            modelBuilder.Entity("Investments.Domain.Trade", b =>
                {
                    b.HasOne("Investments.Domain.Security", null)
                        .WithMany()
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trades_securities_security_id");
                });

            modelBuilder.Entity("Investments.Domain.ManualAsset", b =>
                {
                    b.Navigation("Valuations");
                });
#pragma warning restore 612, 618
        }
    }
}
